from CursoPresencial import CursoPresencial
from CursoOnline import CursoOnline


cp1 = CursoPresencial(1, 'POO Avanzada', 6, 'Dr. Pérez', 3, 'C/Mayor 12', 'Aula 2.4')
cp2 = CursoPresencial(2, 'Bases de Datos', 5, 'Dra. López', 2, 'C/Norte 8', 'Aula 1.1')

co1 = CursoOnline(3, 'Python Web', 4, 'Ing. Ramos', 5, 'Moodle', 'https://moodle.com/python')
co2 = CursoOnline(4, 'Docker Basico', 3, 'Ing. Diaz', 4, 'Classroom', 'https://classroom.com/docker')


print('=== ESTADO INICIAL DE LOS CURSOS ===')
print(cp1)
print(cp2)
print(co1)
print(co2)
input()
print('=== MATRICULAMOS ALUMNOS EN CURSO PRESENCIAL (ID 1) ===')
print('Intentamos matricular alumnos con ID: 101, 102, 103 y 104')
print(f'Resultado matrícula 101: {CursoPresencial.matricular(cp1, 101)}')
print(f'Resultado matrícula 101: {CursoPresencial.matricular(cp1, 102)}')
print(f'Resultado matrícula 101: {CursoPresencial.matricular(cp1, 103)}')
print(f'Resultado matrícula 101 (deberia fallar por falta de plazas): {CursoPresencial.matricular(cp1, 104)}')
print('\nEstado tras matriculas:')
print(cp1)
input()
print('=== MATRICULAMOS ALUMNOS EN CURSO ONLINE (ID 3) ===')
print('Matriculamos alumnos con ID 201 y 202')
CursoOnline.matricular(co1, 201)
CursoOnline.matricular(co1, 202)
print(co1)
input()
print('=== PASAMOS LISTA EN CURSO PRESENCIAL ===')
print('Dia 1 -> Fecha: 2025-02-10')
print('Lista recibida: [101, 103, 999] (999 no esta matriculado)')
CursoPresencial.pasar_lista(cp1, '2025-02-10', [101, 103, 999])
print('\nDia 2 -> Fecha: 2025-02-10')
print('Lista recibida: [102, 103]')
CursoPresencial.pasar_lista(cp1, '2025-02-12', [102, 103])
print('\nAsistencia registrada:')
print(cp1.asistencia)
input()
print('=== GENERAMOS REUNION EN CURSO ONLINE ===')
print('Generamos enlace a la reunion (deberia ser URL base + 10 digitos aleatorios)')
print(f'Enlace generado: {CursoOnline.generar_reunion(co1)}')
input()
print('=== CALCULO DE COSTES ===')
print(f'Coste curso presencial: {CursoPresencial.calcular_coste(cp1)}€')
print(f'Coste curso online: {CursoOnline.calcular_coste(co1)}€')
input()
print('=== COMPROBAMOS IGUALDAD Y HASH ===')
print('Generamos un nuevo curso con el mismo ID que cp1 (ID = 1),\n' 
'pero con nombre, profesor y datos distintos.')
cp1_duplicado = CursoPresencial(1, 'adfd', 999999, 'don pimpon', '20', 'gerge', 'wgger')
print('\nComprobamos igualdad entre cp1 y cp1_duplicado:')
print(f'Resultado (deberia ser True porque comparten ID): {cp1 == cp1_duplicado}')
print('\nAhora comparamos cp1 con cp2 (ID distintos):')
print(f'Resultado (deberia ser False): {cp1 == cp2}')
print('\nCreamos un set e introducimos ambos cursos con ID = 1')
print('El set elimina duplicados segun __hash__ y __eq__.')
set_cursos = set([cp1, cp1_duplicado])
print(f'Longitud del set (deberia ser 1): {len(set_cursos)}')